name: build, package & release
on:
  push:
    tags: 
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: publish app
        working-directory: src/wfh-log-wpf
        run: |
          dotnet publish -p:PublishProfile=FolderProfile
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./wfh-log-wpf/wfh-log-wpf/bin/Release/net6.0-windows/publish/win-x64/wfh-log-wpf.exe
          asset_name: wfh-log-wpf.exe
          asset_content_type: application/octet-stream
