name: build, package & release
on:
  push:
    tags: 
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: restore & build
        working-directory: src/wfh-log-wpf
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet publish -p:PublishProfile=FolderProfile